### PR TITLE
Admin fixes

### PR DESCRIPTION
**Pull request by lauripalonen**
- token service can now handle user deletation requested by admin user
    - user role is now included in the user jwt
- settings page is now hidden from header if user is non-admin
- user management page shows "Not authorized", if non-admin user is attempting to access the page by direct url
- attempted to fix flakyness of "reset file" test by slightly increasing the wait when reset button is pressed
- some comment clean up done

### CODE REVIEW

**Comment by lauripalonen** [comment]
Token service throws "Error fetching refresh token", when user connects to Gitlab and attempts to view repos in Repositories page.

**Comment by lauripalonen** [comment]
Refresh token error above was fixed locally by updating .env-variables. Remotely should be ok!

**Comment by jkotima** [comment]
Looks good, nice job

**Review by jkotima — APPROVED** [review]

**Review by gitblast — COMMENTED** [review]
looks good

**Pull request merged**
